#!/usr/bin/env node
// runstrip 动效取证：开始审阅 → pending→running(滑行)→completed(落墨) 全级联录帧
import { spawn } from "node:child_process";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const URL_APP = "http://localhost:1420";
const OUT = new URL(".", import.meta.url).pathname + "shots-runstrip";
mkdirSync(OUT, { recursive: true });
const DOC = "远程办公正在重塑城市的生活节奏。过去三年里，越来越多的知识工作者选择离开一线城市，搬到成本更低的小城镇生活。有人据此断言，办公室的时代已经终结，城市将不可避免地走向衰落。\n这种结论下得为时过早。远程办公的确改变了部分行业的用工方式，但协同密集型的工作仍然高度依赖面对面的交流。研究显示，视频会议无法完全替代白板前的即兴讨论，也难以复现走廊里的偶然碰撞。\n更重要的是，人口流动的数据并不支持单一方向的判断。部分年轻人回流大城市的同时，也有另一批人在小城扎根创业。城市与小镇的兴衰是多重因素交织的结果。";
const profile = mkdtempSync(join(tmpdir(), "argus-rsm-"));
const chrome = spawn("/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", ["--headless=new", "--remote-debugging-port=0", `--user-data-dir=${profile}`, "--no-first-run", "--hide-scrollbars", "about:blank"], { stdio: ["ignore", "ignore", "pipe"] });
process.on("exit", () => { try { chrome.kill(); } catch {} try { rmSync(profile, { recursive: true, force: true }); } catch {} });
const wsUrl = await new Promise((ok, no) => { let b = ""; const t = setTimeout(() => no(new Error("no chrome")), 15000); chrome.stderr.on("data", (d) => { b += d; const m = b.match(/DevTools listening on (ws:\/\/\S+)/); if (m) { clearTimeout(t); ok(m[1]); } }); });
const ws = new WebSocket(wsUrl);
await new Promise((ok) => { ws.onopen = ok; });
let seq = 0; const pending = new Map(); const listeners = [];
ws.onmessage = (e) => { const m = JSON.parse(e.data); if (m.id && pending.has(m.id)) { const p = pending.get(m.id); pending.delete(m.id); m.error ? p.no(new Error(m.error.message)) : p.ok(m.result); } else if (m.method) listeners.forEach((f) => f(m)); };
const send = (m, p = {}, sid) => new Promise((ok, no) => { const id = ++seq; pending.set(id, { ok, no }); ws.send(JSON.stringify({ id, method: m, params: p, ...(sid ? { sessionId: sid } : {}) })); });
const { targetId } = await send("Target.createTarget", { url: "about:blank" });
const { sessionId } = await send("Target.attachToTarget", { targetId, flatten: true });
const cdp = (m, p) => send(m, p, sessionId);
await cdp("Page.enable");
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const js = async (code) => { const r = await cdp("Runtime.evaluate", { expression: code, awaitPromise: true, returnByValue: true }); if (r.exceptionDetails) throw new Error((r.exceptionDetails.exception?.description || "").split("\n")[0]); return r.result.value; };
await cdp("Emulation.setDeviceMetricsOverride", { width: 1240, height: 800, deviceScaleFactor: 1, mobile: false });
await cdp("Emulation.setEmulatedMedia", { features: [{ name: "prefers-color-scheme", value: "light" }] });
await cdp("Page.navigate", { url: URL_APP });
await sleep(1500);
await js(`(async () => {
  const dc = (s) => { const el = document.querySelector(s); if (!el) throw new Error("找不到：" + s); el.click(); };
  const sv = (s, v) => { const el = document.querySelector(s); el.focus(); el.value = v; el.dispatchEvent(new Event("input", { bubbles: true })); };
  const w8 = (s, ms = 15000) => { const t0 = Date.now(); return new Promise((ok, no) => { const t = () => { if (document.querySelector(s)) return ok(1); if (Date.now() - t0 > ms) return no(new Error("超时 " + s)); setTimeout(t, 120); }; t(); }); };
  dc('.ob-alt .ob-card'); await w8('.ob-fields input');
  sv('[data-test=ob-custom-baseurl]', 'http://127.0.0.1:8932/v1'); sv('.ob-fields input[type=password]', 'sk-mock'); sv('[data-test=ob-custom-model]', 'mock-pro');
  await new Promise(r => setTimeout(r, 250)); dc('[data-test=ob-save]'); await w8('.doc-input');
  sv('.doc-input', ${JSON.stringify(DOC)});
  await new Promise(r => setTimeout(r, 300));
  return true;
})()`);
const frames = [];
const onFrame = (m) => { if (m.sessionId !== sessionId || m.method !== "Page.screencastFrame") return; frames.push(Buffer.from(m.params.data, "base64")); cdp("Page.screencastFrameAck", { sessionId: m.params.sessionId }).catch(() => {}); };
listeners.push(onFrame);
await cdp("Page.startScreencast", { format: "jpeg", quality: 88, everyNthFrame: 1 });
await js(`document.querySelector('.new-actions .cta').click()`);
await sleep(3500);
await cdp("Page.stopScreencast").catch(() => {});
listeners.splice(listeners.indexOf(onFrame), 1);
if (frames.length >= 3) {
  writeFileSync(`${OUT}/rs-cascade-start.jpg`, frames[0]);
  writeFileSync(`${OUT}/rs-cascade-mid1.jpg`, frames[Math.floor(frames.length * 0.35)]);
  writeFileSync(`${OUT}/rs-cascade-mid2.jpg`, frames[Math.floor(frames.length * 0.6)]);
  writeFileSync(`${OUT}/rs-cascade-end.jpg`, frames[frames.length - 1]);
  console.log(`🎬 rs-cascade: ${frames.length} 帧 → 四帧已存`);
} else console.log("⚠️ 只收到", frames.length, "帧");
chrome.kill();
process.exit(0);
